### ISSUE TITLE
Mapathon Summary Page throwing a 404 error

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/galaxy-ui#11]
While accessing the link directly https://galaxy.hotosm.org/mapathon-summary-report - there is a 404 error. However while accessing the page through explore data section, it works well

Expected behaviour: https://galaxy.hotosm.org/mapathon-summary-report should load without any errors while accessed directly using the link

cc @d-rita

**Comment by omranlm** [comment]
@ramyaragupathy 
This is a web server related error. In the web server configuration when hosting a single page app such as react js in our case. The 404 and 403 errors should be redirected to index.html page so it depends on the hosting env

I we wanna continue with github pages, we can't use React browser routers, we need to change to react hash routers.

@dakotabenjamin I would suggest to host the UI on S3

**Comment by d-rita** [comment]
According to the[ create-react-documentation](https://create-react-app.dev/docs/deployment/#notes-on-client-side-routing): 
- we could use the Hash Router from react-router instead of the Browser Router which would essentially add an extra `#` before each route. So, it would be `https://galaxy.hotosm.org/#/explore`.
- Alternatively, we could follow the [recommended guide ](https://github.com/rafgraph/spa-github-pages)where we create a custom 404 file that redirects to the index.html page depending on the route.

**Comment by ramyaragupathy** [comment]
Fixed through https://github.com/hotosm/galaxy-ui/pull/15
