### ISSUE TITLE
Handling usernames with one character

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/galaxy-ui#111]
In the user report section when I input username with just single characters, I get the following error message:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/12103383/176076580-4acfc82d-b859-4e60-84cf-9705364ec5ad.png">

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/12103383/176076809-d13c7c1a-81bd-4931-821e-ee9c35bd72ef.png">

Can we handle this much better than having to come out of of the user report page? Like disabling the submit button or showing an error message within the user report page?

This only happens when **_all the input usernames have  just single character_**. It is not an issue when such names are combined with other usernames with more than one character.

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/12103383/176077126-7347176e-bf93-483b-b1a5-b7bf329cbd42.png">

**Comment by d-rita** [comment]
Tested this out and got this. What I realised is that the single character usernames are not being added to the request sent to the API. 
<img width="1411" alt="error" src="https://user-images.githubusercontent.com/31903212/176444151-597d45bc-920e-46f7-9f47-c784e240873c.png">

Because they don't match this regex pattern - (that checks that it is a multiple-character word), the usernames are not added: https://github.com/hotosm/galaxy-ui/blob/4498c360e92071c2ee37ec28a3b6741a5d2cdece/src/utils/formatInputs.js#L23 https://github.com/hotosm/galaxy-ui/blob/4498c360e92071c2ee37ec28a3b6741a5d2cdece/src/utils/formatInputs.js#L24

The proposed solution is to either remove the regex or alter it to fit different usernames based on what OSM permits via username restrictions.
