### ISSUE TITLE
Better user experience while fetching user group reports

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/galaxy-ui#34]
From https://github.com/hotosm/galaxy-ui/pull/13#issuecomment-1020941720 - two enhancements to the user group report page

1. While loading user report page data , I am getting No data found for a while and after few seconds I am getting the data back , we need to add some loading options while fetching the data and remove it after we got the data and display it

https://user-images.githubusercontent.com/36752999/150940434-73ade5fb-ee79-435a-8396-612c8d555a25.png

2. Displaying No Data found message when nothing is returned from API instead of 0

![image](https://user-images.githubusercontent.com/12103383/151015059-d26e8acb-0d42-48d5-8333-b05175946097.png)

cc @itskshitiz321 @d-rita

**Comment by harry-wood** [comment]
Yeah I noticed it says "Loading..." for about 2 seconds and then the table column headings appear, then the slow query actually runs for 20 seconds or so, and there's no "Loading..." message during that time.

**Comment by d-rita** [comment]
Thank you for pointing that out @harry-wood. I am working on this task for the current sprint. Because the user group report relies on more than one query to fetch information, it takes a while for the results to show. So, I will be adding a loading indicator as the rows expand for each user added. That way users can know if there is any more information to wait for.
