### ISSUE TITLE
[USER] Let users be able to sort mapathon table results

### ISSUE THREAD

**Issue by d-rita** [hotosm/galaxy-ui#70]
This was feedback got from a user interview. Currently, there is no particular order to the results returned, i.e. not sorted by name or any of the statistics. The goal would be to be able to sort by at least one of the metrics like buildings added.

**Comment by itskshitiz321** [comment]
There will be multiple user needs , such as sorting by ascending descending , Search or any of the metrices we provide . I suggest to use  table libraries so that they will have everything sorted out by themselves after we populate the data in one shot, We don't have to worry about those functionality . One I used previously is [this ](https://datatables.net/) awesome library !

**Comment by d-rita** [comment]
Looking at the [react table](https://react-table-v7.tanstack.com/docs/examples/sorting) library in conjunction with the [react-csv](https://www.npmjs.com/package/react-csv) library for CSV downloads. That is, vis-a-vis the datatables jquery library earlier suggested.
